/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PropostaIdRouteImport } from './routes/proposta.$id'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppPropostasRouteImport } from './routes/app.propostas'
import { Route as AppProjetosRouteImport } from './routes/app.projetos'
import { Route as AppPagamentosRouteImport } from './routes/app.pagamentos'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppMarketingRouteImport } from './routes/app.marketing'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppHorasRouteImport } from './routes/app.horas'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEscopoRouteImport } from './routes/app.escopo'
import { Route as AppDocumentacaoRouteImport } from './routes/app.documentacao'
import { Route as AppDiarioRouteImport } from './routes/app.diario'
import { Route as AppDesenvolvimentoRouteImport } from './routes/app.desenvolvimento'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppContratosRouteImport } from './routes/app.contratos'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppBotAdminRouteImport } from './routes/app.bot-admin'
import { Route as AppBotRouteImport } from './routes/app.bot'
import { Route as AppBibliotecaRouteImport } from './routes/app.biblioteca'
import { Route as AppBaseRouteImport } from './routes/app.base'
import { Route as AppAutomacoesRouteImport } from './routes/app.automacoes'
import { Route as AppAtividadeRouteImport } from './routes/app.atividade'
import { Route as AppAtendimentoRouteImport } from './routes/app.atendimento'
import { Route as AppAprovacoesRouteImport } from './routes/app.aprovacoes'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAcademiaRouteImport } from './routes/app.academia'
import { Route as ApiProposalsRouteImport } from './routes/api.proposals'
import { Route as ApiProjectsRouteImport } from './routes/api.projects'
import { Route as ApiPaymentRouteImport } from './routes/api.payment'
import { Route as ApiLeadsRouteImport } from './routes/api.leads'
import { Route as ApiLeadRouteImport } from './routes/api.lead'
import { Route as ApiDashboardRouteImport } from './routes/api.dashboard'
import { Route as ClienteOnboardingProjetoRouteImport } from './routes/cliente.onboarding.$projeto'
import { Route as ApiProposalTokenRouteImport } from './routes/api.proposal.$token'
import { Route as ApiProjectTokenRouteImport } from './routes/api.project.$token'
import { Route as ApiPaymentWebhookRouteImport } from './routes/api.payment.webhook'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PropostaIdRoute = PropostaIdRouteImport.update({
  id: '/proposta/$id',
  path: '/proposta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppPagamentosRoute = AppPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppHorasRoute = AppHorasRouteImport.update({
  id: '/horas',
  path: '/horas',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEscopoRoute = AppEscopoRouteImport.update({
  id: '/escopo',
  path: '/escopo',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentacaoRoute = AppDocumentacaoRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => AppRoute,
} as any)
const AppDiarioRoute = AppDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AppRoute,
} as any)
const AppDesenvolvimentoRoute = AppDesenvolvimentoRouteImport.update({
  id: '/desenvolvimento',
  path: '/desenvolvimento',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBotAdminRoute = AppBotAdminRouteImport.update({
  id: '/bot-admin',
  path: '/bot-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppBotRoute = AppBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppBaseRoute = AppBaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAtividadeRoute = AppAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AppRoute,
} as any)
const AppAtendimentoRoute = AppAtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => AppRoute,
} as any)
const AppAprovacoesRoute = AppAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademiaRoute = AppAcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => AppRoute,
} as any)
const ApiProposalsRoute = ApiProposalsRouteImport.update({
  id: '/api/proposals',
  path: '/api/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentRoute = ApiPaymentRouteImport.update({
  id: '/api/payment',
  path: '/api/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteOnboardingProjetoRoute =
  ClienteOnboardingProjetoRouteImport.update({
    id: '/onboarding/$projeto',
    path: '/onboarding/$projeto',
    getParentRoute: () => ClienteRoute,
  } as any)
const ApiProposalTokenRoute = ApiProposalTokenRouteImport.update({
  id: '/api/proposal/$token',
  path: '/api/proposal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectTokenRoute = ApiProjectTokenRouteImport.update({
  id: '/api/project/$token',
  path: '/api/project/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookRoute = ApiPaymentWebhookRouteImport.update({
  id: '/webhook',
  path: '/webhook',
  getParentRoute: () => ApiPaymentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/payment': typeof ApiPaymentRouteWithChildren
  '/api/projects': typeof ApiProjectsRoute
  '/api/proposals': typeof ApiProposalsRoute
  '/app/academia': typeof AppAcademiaRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/aprovacoes': typeof AppAprovacoesRoute
  '/app/atendimento': typeof AppAtendimentoRoute
  '/app/atividade': typeof AppAtividadeRoute
  '/app/automacoes': typeof AppAutomacoesRoute
  '/app/base': typeof AppBaseRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/bot': typeof AppBotRoute
  '/app/bot-admin': typeof AppBotAdminRoute
  '/app/chat': typeof AppChatRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/crm': typeof AppCrmRoute
  '/app/desenvolvimento': typeof AppDesenvolvimentoRoute
  '/app/diario': typeof AppDiarioRoute
  '/app/documentacao': typeof AppDocumentacaoRoute
  '/app/escopo': typeof AppEscopoRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/health': typeof AppHealthRoute
  '/app/horas': typeof AppHorasRoute
  '/app/ia': typeof AppIaRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/templates': typeof AppTemplatesRoute
  '/proposta/$id': typeof PropostaIdRoute
  '/app/': typeof AppIndexRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/project/$token': typeof ApiProjectTokenRoute
  '/api/proposal/$token': typeof ApiProposalTokenRoute
  '/cliente/onboarding/$projeto': typeof ClienteOnboardingProjetoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/payment': typeof ApiPaymentRouteWithChildren
  '/api/projects': typeof ApiProjectsRoute
  '/api/proposals': typeof ApiProposalsRoute
  '/app/academia': typeof AppAcademiaRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/aprovacoes': typeof AppAprovacoesRoute
  '/app/atendimento': typeof AppAtendimentoRoute
  '/app/atividade': typeof AppAtividadeRoute
  '/app/automacoes': typeof AppAutomacoesRoute
  '/app/base': typeof AppBaseRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/bot': typeof AppBotRoute
  '/app/bot-admin': typeof AppBotAdminRoute
  '/app/chat': typeof AppChatRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/crm': typeof AppCrmRoute
  '/app/desenvolvimento': typeof AppDesenvolvimentoRoute
  '/app/diario': typeof AppDiarioRoute
  '/app/documentacao': typeof AppDocumentacaoRoute
  '/app/escopo': typeof AppEscopoRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/health': typeof AppHealthRoute
  '/app/horas': typeof AppHorasRoute
  '/app/ia': typeof AppIaRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/templates': typeof AppTemplatesRoute
  '/proposta/$id': typeof PropostaIdRoute
  '/app': typeof AppIndexRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/project/$token': typeof ApiProjectTokenRoute
  '/api/proposal/$token': typeof ApiProposalTokenRoute
  '/cliente/onboarding/$projeto': typeof ClienteOnboardingProjetoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/payment': typeof ApiPaymentRouteWithChildren
  '/api/projects': typeof ApiProjectsRoute
  '/api/proposals': typeof ApiProposalsRoute
  '/app/academia': typeof AppAcademiaRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/aprovacoes': typeof AppAprovacoesRoute
  '/app/atendimento': typeof AppAtendimentoRoute
  '/app/atividade': typeof AppAtividadeRoute
  '/app/automacoes': typeof AppAutomacoesRoute
  '/app/base': typeof AppBaseRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/bot': typeof AppBotRoute
  '/app/bot-admin': typeof AppBotAdminRoute
  '/app/chat': typeof AppChatRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/crm': typeof AppCrmRoute
  '/app/desenvolvimento': typeof AppDesenvolvimentoRoute
  '/app/diario': typeof AppDiarioRoute
  '/app/documentacao': typeof AppDocumentacaoRoute
  '/app/escopo': typeof AppEscopoRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/health': typeof AppHealthRoute
  '/app/horas': typeof AppHorasRoute
  '/app/ia': typeof AppIaRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/templates': typeof AppTemplatesRoute
  '/proposta/$id': typeof PropostaIdRoute
  '/app/': typeof AppIndexRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/project/$token': typeof ApiProjectTokenRoute
  '/api/proposal/$token': typeof ApiProposalTokenRoute
  '/cliente/onboarding/$projeto': typeof ClienteOnboardingProjetoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cliente'
    | '/login'
    | '/api/dashboard'
    | '/api/lead'
    | '/api/leads'
    | '/api/payment'
    | '/api/projects'
    | '/api/proposals'
    | '/app/academia'
    | '/app/analytics'
    | '/app/aprovacoes'
    | '/app/atendimento'
    | '/app/atividade'
    | '/app/automacoes'
    | '/app/base'
    | '/app/biblioteca'
    | '/app/bot'
    | '/app/bot-admin'
    | '/app/chat'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/crm'
    | '/app/desenvolvimento'
    | '/app/diario'
    | '/app/documentacao'
    | '/app/escopo'
    | '/app/financeiro'
    | '/app/health'
    | '/app/horas'
    | '/app/ia'
    | '/app/inbox'
    | '/app/leads'
    | '/app/marketing'
    | '/app/marketplace'
    | '/app/pagamentos'
    | '/app/projetos'
    | '/app/propostas'
    | '/app/suporte'
    | '/app/templates'
    | '/proposta/$id'
    | '/app/'
    | '/api/payment/webhook'
    | '/api/project/$token'
    | '/api/proposal/$token'
    | '/cliente/onboarding/$projeto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cliente'
    | '/login'
    | '/api/dashboard'
    | '/api/lead'
    | '/api/leads'
    | '/api/payment'
    | '/api/projects'
    | '/api/proposals'
    | '/app/academia'
    | '/app/analytics'
    | '/app/aprovacoes'
    | '/app/atendimento'
    | '/app/atividade'
    | '/app/automacoes'
    | '/app/base'
    | '/app/biblioteca'
    | '/app/bot'
    | '/app/bot-admin'
    | '/app/chat'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/crm'
    | '/app/desenvolvimento'
    | '/app/diario'
    | '/app/documentacao'
    | '/app/escopo'
    | '/app/financeiro'
    | '/app/health'
    | '/app/horas'
    | '/app/ia'
    | '/app/inbox'
    | '/app/leads'
    | '/app/marketing'
    | '/app/marketplace'
    | '/app/pagamentos'
    | '/app/projetos'
    | '/app/propostas'
    | '/app/suporte'
    | '/app/templates'
    | '/proposta/$id'
    | '/app'
    | '/api/payment/webhook'
    | '/api/project/$token'
    | '/api/proposal/$token'
    | '/cliente/onboarding/$projeto'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cliente'
    | '/login'
    | '/api/dashboard'
    | '/api/lead'
    | '/api/leads'
    | '/api/payment'
    | '/api/projects'
    | '/api/proposals'
    | '/app/academia'
    | '/app/analytics'
    | '/app/aprovacoes'
    | '/app/atendimento'
    | '/app/atividade'
    | '/app/automacoes'
    | '/app/base'
    | '/app/biblioteca'
    | '/app/bot'
    | '/app/bot-admin'
    | '/app/chat'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/crm'
    | '/app/desenvolvimento'
    | '/app/diario'
    | '/app/documentacao'
    | '/app/escopo'
    | '/app/financeiro'
    | '/app/health'
    | '/app/horas'
    | '/app/ia'
    | '/app/inbox'
    | '/app/leads'
    | '/app/marketing'
    | '/app/marketplace'
    | '/app/pagamentos'
    | '/app/projetos'
    | '/app/propostas'
    | '/app/suporte'
    | '/app/templates'
    | '/proposta/$id'
    | '/app/'
    | '/api/payment/webhook'
    | '/api/project/$token'
    | '/api/proposal/$token'
    | '/cliente/onboarding/$projeto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ClienteRoute: typeof ClienteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiLeadRoute: typeof ApiLeadRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiPaymentRoute: typeof ApiPaymentRouteWithChildren
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiProposalsRoute: typeof ApiProposalsRoute
  PropostaIdRoute: typeof PropostaIdRoute
  ApiProjectTokenRoute: typeof ApiProjectTokenRoute
  ApiProposalTokenRoute: typeof ApiProposalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/proposta/$id': {
      id: '/proposta/$id'
      path: '/proposta/$id'
      fullPath: '/proposta/$id'
      preLoaderRoute: typeof PropostaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas': {
      id: '/app/propostas'
      path: '/propostas'
      fullPath: '/app/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos': {
      id: '/app/projetos'
      path: '/projetos'
      fullPath: '/app/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pagamentos': {
      id: '/app/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/pagamentos'
      preLoaderRoute: typeof AppPagamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/horas': {
      id: '/app/horas'
      path: '/horas'
      fullPath: '/app/horas'
      preLoaderRoute: typeof AppHorasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escopo': {
      id: '/app/escopo'
      path: '/escopo'
      fullPath: '/app/escopo'
      preLoaderRoute: typeof AppEscopoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentacao': {
      id: '/app/documentacao'
      path: '/documentacao'
      fullPath: '/app/documentacao'
      preLoaderRoute: typeof AppDocumentacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diario': {
      id: '/app/diario'
      path: '/diario'
      fullPath: '/app/diario'
      preLoaderRoute: typeof AppDiarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/desenvolvimento': {
      id: '/app/desenvolvimento'
      path: '/desenvolvimento'
      fullPath: '/app/desenvolvimento'
      preLoaderRoute: typeof AppDesenvolvimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratos': {
      id: '/app/contratos'
      path: '/contratos'
      fullPath: '/app/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bot-admin': {
      id: '/app/bot-admin'
      path: '/bot-admin'
      fullPath: '/app/bot-admin'
      preLoaderRoute: typeof AppBotAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bot': {
      id: '/app/bot'
      path: '/bot'
      fullPath: '/app/bot'
      preLoaderRoute: typeof AppBotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/biblioteca': {
      id: '/app/biblioteca'
      path: '/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/base': {
      id: '/app/base'
      path: '/base'
      fullPath: '/app/base'
      preLoaderRoute: typeof AppBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automacoes': {
      id: '/app/automacoes'
      path: '/automacoes'
      fullPath: '/app/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atividade': {
      id: '/app/atividade'
      path: '/atividade'
      fullPath: '/app/atividade'
      preLoaderRoute: typeof AppAtividadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atendimento': {
      id: '/app/atendimento'
      path: '/atendimento'
      fullPath: '/app/atendimento'
      preLoaderRoute: typeof AppAtendimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aprovacoes': {
      id: '/app/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/app/aprovacoes'
      preLoaderRoute: typeof AppAprovacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academia': {
      id: '/app/academia'
      path: '/academia'
      fullPath: '/app/academia'
      preLoaderRoute: typeof AppAcademiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/proposals': {
      id: '/api/proposals'
      path: '/api/proposals'
      fullPath: '/api/proposals'
      preLoaderRoute: typeof ApiProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment': {
      id: '/api/payment'
      path: '/api/payment'
      fullPath: '/api/payment'
      preLoaderRoute: typeof ApiPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/onboarding/$projeto': {
      id: '/cliente/onboarding/$projeto'
      path: '/onboarding/$projeto'
      fullPath: '/cliente/onboarding/$projeto'
      preLoaderRoute: typeof ClienteOnboardingProjetoRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/api/proposal/$token': {
      id: '/api/proposal/$token'
      path: '/api/proposal/$token'
      fullPath: '/api/proposal/$token'
      preLoaderRoute: typeof ApiProposalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project/$token': {
      id: '/api/project/$token'
      path: '/api/project/$token'
      fullPath: '/api/project/$token'
      preLoaderRoute: typeof ApiProjectTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook': {
      id: '/api/payment/webhook'
      path: '/webhook'
      fullPath: '/api/payment/webhook'
      preLoaderRoute: typeof ApiPaymentWebhookRouteImport
      parentRoute: typeof ApiPaymentRoute
    }
  }
}

interface AppRouteChildren {
  AppAcademiaRoute: typeof AppAcademiaRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAprovacoesRoute: typeof AppAprovacoesRoute
  AppAtendimentoRoute: typeof AppAtendimentoRoute
  AppAtividadeRoute: typeof AppAtividadeRoute
  AppAutomacoesRoute: typeof AppAutomacoesRoute
  AppBaseRoute: typeof AppBaseRoute
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppBotRoute: typeof AppBotRoute
  AppBotAdminRoute: typeof AppBotAdminRoute
  AppChatRoute: typeof AppChatRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContratosRoute: typeof AppContratosRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDesenvolvimentoRoute: typeof AppDesenvolvimentoRoute
  AppDiarioRoute: typeof AppDiarioRoute
  AppDocumentacaoRoute: typeof AppDocumentacaoRoute
  AppEscopoRoute: typeof AppEscopoRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppHealthRoute: typeof AppHealthRoute
  AppHorasRoute: typeof AppHorasRoute
  AppIaRoute: typeof AppIaRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppPagamentosRoute: typeof AppPagamentosRoute
  AppProjetosRoute: typeof AppProjetosRoute
  AppPropostasRoute: typeof AppPropostasRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademiaRoute: AppAcademiaRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAprovacoesRoute: AppAprovacoesRoute,
  AppAtendimentoRoute: AppAtendimentoRoute,
  AppAtividadeRoute: AppAtividadeRoute,
  AppAutomacoesRoute: AppAutomacoesRoute,
  AppBaseRoute: AppBaseRoute,
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppBotRoute: AppBotRoute,
  AppBotAdminRoute: AppBotAdminRoute,
  AppChatRoute: AppChatRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContratosRoute: AppContratosRoute,
  AppCrmRoute: AppCrmRoute,
  AppDesenvolvimentoRoute: AppDesenvolvimentoRoute,
  AppDiarioRoute: AppDiarioRoute,
  AppDocumentacaoRoute: AppDocumentacaoRoute,
  AppEscopoRoute: AppEscopoRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppHealthRoute: AppHealthRoute,
  AppHorasRoute: AppHorasRoute,
  AppIaRoute: AppIaRoute,
  AppInboxRoute: AppInboxRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppPagamentosRoute: AppPagamentosRoute,
  AppProjetosRoute: AppProjetosRoute,
  AppPropostasRoute: AppPropostasRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ClienteRouteChildren {
  ClienteOnboardingProjetoRoute: typeof ClienteOnboardingProjetoRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteOnboardingProjetoRoute: ClienteOnboardingProjetoRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

interface ApiPaymentRouteChildren {
  ApiPaymentWebhookRoute: typeof ApiPaymentWebhookRoute
}

const ApiPaymentRouteChildren: ApiPaymentRouteChildren = {
  ApiPaymentWebhookRoute: ApiPaymentWebhookRoute,
}

const ApiPaymentRouteWithChildren = ApiPaymentRoute._addFileChildren(
  ApiPaymentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ClienteRoute: ClienteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiLeadRoute: ApiLeadRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiPaymentRoute: ApiPaymentRouteWithChildren,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiProposalsRoute: ApiProposalsRoute,
  PropostaIdRoute: PropostaIdRoute,
  ApiProjectTokenRoute: ApiProjectTokenRoute,
  ApiProposalTokenRoute: ApiProposalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
