/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppPropostasRouteImport } from './routes/app.propostas'
import { Route as AppProjetosRouteImport } from './routes/app.projetos'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppContratosRouteImport } from './routes/app.contratos'
import { Route as AppClientesRouteImport } from './routes/app.clientes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/clientes'
    | '/app/contratos'
    | '/app/financeiro'
    | '/app/inbox'
    | '/app/projetos'
    | '/app/propostas'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/clientes'
    | '/app/contratos'
    | '/app/financeiro'
    | '/app/inbox'
    | '/app/projetos'
    | '/app/propostas'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/clientes'
    | '/app/contratos'
    | '/app/financeiro'
    | '/app/inbox'
    | '/app/projetos'
    | '/app/propostas'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas': {
      id: '/app/propostas'
      path: '/propostas'
      fullPath: '/app/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos': {
      id: '/app/projetos'
      path: '/projetos'
      fullPath: '/app/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratos': {
      id: '/app/contratos'
      path: '/contratos'
      fullPath: '/app/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppContratosRoute: typeof AppContratosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppInboxRoute: typeof AppInboxRoute
  AppProjetosRoute: typeof AppProjetosRoute
  AppPropostasRoute: typeof AppPropostasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppContratosRoute: AppContratosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppInboxRoute: AppInboxRoute,
  AppProjetosRoute: AppProjetosRoute,
  AppPropostasRoute: AppPropostasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
