/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PropostaIdRouteImport } from './routes/proposta.$id'
import { Route as AppPropostasRouteImport } from './routes/app.propostas'
import { Route as AppProjetosRouteImport } from './routes/app.projetos'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppHorasRouteImport } from './routes/app.horas'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEscopoRouteImport } from './routes/app.escopo'
import { Route as AppDiarioRouteImport } from './routes/app.diario'
import { Route as AppDesenvolvimentoRouteImport } from './routes/app.desenvolvimento'
import { Route as AppContratosRouteImport } from './routes/app.contratos'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppBaseRouteImport } from './routes/app.base'
import { Route as AppAtividadeRouteImport } from './routes/app.atividade'
import { Route as AppAtendimentoRouteImport } from './routes/app.atendimento'
import { Route as AppAprovacoesRouteImport } from './routes/app.aprovacoes'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ClienteOnboardingProjetoRouteImport } from './routes/cliente.onboarding.$projeto'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PropostaIdRoute = PropostaIdRouteImport.update({
  id: '/proposta/$id',
  path: '/proposta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppHorasRoute = AppHorasRouteImport.update({
  id: '/horas',
  path: '/horas',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEscopoRoute = AppEscopoRouteImport.update({
  id: '/escopo',
  path: '/escopo',
  getParentRoute: () => AppRoute,
} as any)
const AppDiarioRoute = AppDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AppRoute,
} as any)
const AppDesenvolvimentoRoute = AppDesenvolvimentoRouteImport.update({
  id: '/desenvolvimento',
  path: '/desenvolvimento',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBaseRoute = AppBaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => AppRoute,
} as any)
const AppAtividadeRoute = AppAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AppRoute,
} as any)
const AppAtendimentoRoute = AppAtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => AppRoute,
} as any)
const AppAprovacoesRoute = AppAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClienteOnboardingProjetoRoute =
  ClienteOnboardingProjetoRouteImport.update({
    id: '/onboarding/$projeto',
    path: '/onboarding/$projeto',
    getParentRoute: () => ClienteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/aprovacoes': typeof AppAprovacoesRoute
  '/app/atendimento': typeof AppAtendimentoRoute
  '/app/atividade': typeof AppAtividadeRoute
  '/app/base': typeof AppBaseRoute
  '/app/chat': typeof AppChatRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/desenvolvimento': typeof AppDesenvolvimentoRoute
  '/app/diario': typeof AppDiarioRoute
  '/app/escopo': typeof AppEscopoRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/health': typeof AppHealthRoute
  '/app/horas': typeof AppHorasRoute
  '/app/ia': typeof AppIaRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/propostas': typeof AppPropostasRoute
  '/proposta/$id': typeof PropostaIdRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/cliente/onboarding/$projeto': typeof ClienteOnboardingProjetoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/aprovacoes': typeof AppAprovacoesRoute
  '/app/atendimento': typeof AppAtendimentoRoute
  '/app/atividade': typeof AppAtividadeRoute
  '/app/base': typeof AppBaseRoute
  '/app/chat': typeof AppChatRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/desenvolvimento': typeof AppDesenvolvimentoRoute
  '/app/diario': typeof AppDiarioRoute
  '/app/escopo': typeof AppEscopoRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/health': typeof AppHealthRoute
  '/app/horas': typeof AppHorasRoute
  '/app/ia': typeof AppIaRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/propostas': typeof AppPropostasRoute
  '/proposta/$id': typeof PropostaIdRoute
  '/app': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/cliente/onboarding/$projeto': typeof ClienteOnboardingProjetoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/aprovacoes': typeof AppAprovacoesRoute
  '/app/atendimento': typeof AppAtendimentoRoute
  '/app/atividade': typeof AppAtividadeRoute
  '/app/base': typeof AppBaseRoute
  '/app/chat': typeof AppChatRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/desenvolvimento': typeof AppDesenvolvimentoRoute
  '/app/diario': typeof AppDiarioRoute
  '/app/escopo': typeof AppEscopoRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/health': typeof AppHealthRoute
  '/app/horas': typeof AppHorasRoute
  '/app/ia': typeof AppIaRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/propostas': typeof AppPropostasRoute
  '/proposta/$id': typeof PropostaIdRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/cliente/onboarding/$projeto': typeof ClienteOnboardingProjetoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cliente'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/aprovacoes'
    | '/app/atendimento'
    | '/app/atividade'
    | '/app/base'
    | '/app/chat'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/desenvolvimento'
    | '/app/diario'
    | '/app/escopo'
    | '/app/financeiro'
    | '/app/health'
    | '/app/horas'
    | '/app/ia'
    | '/app/inbox'
    | '/app/projetos'
    | '/app/propostas'
    | '/proposta/$id'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/cliente/onboarding/$projeto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cliente'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/aprovacoes'
    | '/app/atendimento'
    | '/app/atividade'
    | '/app/base'
    | '/app/chat'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/desenvolvimento'
    | '/app/diario'
    | '/app/escopo'
    | '/app/financeiro'
    | '/app/health'
    | '/app/horas'
    | '/app/ia'
    | '/app/inbox'
    | '/app/projetos'
    | '/app/propostas'
    | '/proposta/$id'
    | '/app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/cliente/onboarding/$projeto'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cliente'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/aprovacoes'
    | '/app/atendimento'
    | '/app/atividade'
    | '/app/base'
    | '/app/chat'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/desenvolvimento'
    | '/app/diario'
    | '/app/escopo'
    | '/app/financeiro'
    | '/app/health'
    | '/app/horas'
    | '/app/ia'
    | '/app/inbox'
    | '/app/projetos'
    | '/app/propostas'
    | '/proposta/$id'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/cliente/onboarding/$projeto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ClienteRoute: typeof ClienteRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  PropostaIdRoute: typeof PropostaIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/proposta/$id': {
      id: '/proposta/$id'
      path: '/proposta/$id'
      fullPath: '/proposta/$id'
      preLoaderRoute: typeof PropostaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/propostas': {
      id: '/app/propostas'
      path: '/propostas'
      fullPath: '/app/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos': {
      id: '/app/projetos'
      path: '/projetos'
      fullPath: '/app/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/horas': {
      id: '/app/horas'
      path: '/horas'
      fullPath: '/app/horas'
      preLoaderRoute: typeof AppHorasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escopo': {
      id: '/app/escopo'
      path: '/escopo'
      fullPath: '/app/escopo'
      preLoaderRoute: typeof AppEscopoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diario': {
      id: '/app/diario'
      path: '/diario'
      fullPath: '/app/diario'
      preLoaderRoute: typeof AppDiarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/desenvolvimento': {
      id: '/app/desenvolvimento'
      path: '/desenvolvimento'
      fullPath: '/app/desenvolvimento'
      preLoaderRoute: typeof AppDesenvolvimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratos': {
      id: '/app/contratos'
      path: '/contratos'
      fullPath: '/app/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/base': {
      id: '/app/base'
      path: '/base'
      fullPath: '/app/base'
      preLoaderRoute: typeof AppBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atividade': {
      id: '/app/atividade'
      path: '/atividade'
      fullPath: '/app/atividade'
      preLoaderRoute: typeof AppAtividadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atendimento': {
      id: '/app/atendimento'
      path: '/atendimento'
      fullPath: '/app/atendimento'
      preLoaderRoute: typeof AppAtendimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aprovacoes': {
      id: '/app/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/app/aprovacoes'
      preLoaderRoute: typeof AppAprovacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/onboarding/$projeto': {
      id: '/cliente/onboarding/$projeto'
      path: '/onboarding/$projeto'
      fullPath: '/cliente/onboarding/$projeto'
      preLoaderRoute: typeof ClienteOnboardingProjetoRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAprovacoesRoute: typeof AppAprovacoesRoute
  AppAtendimentoRoute: typeof AppAtendimentoRoute
  AppAtividadeRoute: typeof AppAtividadeRoute
  AppBaseRoute: typeof AppBaseRoute
  AppChatRoute: typeof AppChatRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContratosRoute: typeof AppContratosRoute
  AppDesenvolvimentoRoute: typeof AppDesenvolvimentoRoute
  AppDiarioRoute: typeof AppDiarioRoute
  AppEscopoRoute: typeof AppEscopoRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppHealthRoute: typeof AppHealthRoute
  AppHorasRoute: typeof AppHorasRoute
  AppIaRoute: typeof AppIaRoute
  AppInboxRoute: typeof AppInboxRoute
  AppProjetosRoute: typeof AppProjetosRoute
  AppPropostasRoute: typeof AppPropostasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAprovacoesRoute: AppAprovacoesRoute,
  AppAtendimentoRoute: AppAtendimentoRoute,
  AppAtividadeRoute: AppAtividadeRoute,
  AppBaseRoute: AppBaseRoute,
  AppChatRoute: AppChatRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContratosRoute: AppContratosRoute,
  AppDesenvolvimentoRoute: AppDesenvolvimentoRoute,
  AppDiarioRoute: AppDiarioRoute,
  AppEscopoRoute: AppEscopoRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppHealthRoute: AppHealthRoute,
  AppHorasRoute: AppHorasRoute,
  AppIaRoute: AppIaRoute,
  AppInboxRoute: AppInboxRoute,
  AppProjetosRoute: AppProjetosRoute,
  AppPropostasRoute: AppPropostasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ClienteRouteChildren {
  ClienteOnboardingProjetoRoute: typeof ClienteOnboardingProjetoRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteOnboardingProjetoRoute: ClienteOnboardingProjetoRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ClienteRoute: ClienteRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  PropostaIdRoute: PropostaIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
